version: '3.1'
services:
  cache:
    image: redislabs/redismod:latest
    restart: always
    ports:
      - "6379:6379"
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "4000:4000"
    links:
      - cache
    environment:
      IS_PRODUCTION: 1
      REDIS_HOST: cache
    env_file:
      - .env