version: '3.1'
services:
  cache:
    image: redislabs/redismod:latest
    restart: always
    ports:
      - "6379:6379"
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "4000:4000"
    links:
      - cache
    environment:
      REDIS_HOST: cache
    volumes:
      - ./:/app
    env_file:
      - .env