apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: seasidefm
  name: api-ddns
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: namecheap-ddns
              image: dougflynndev/namecheap-ddns
              imagePullPolicy: Always
              env:
                - name: PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: archive-host
                      key: PASSWORD
                - name: DOMAIN
                  valueFrom:
                    secretKeyRef:
                      name: archive-host
                      key: DOMAIN
                - name: SUB_DOMAINS
                  value: 'api'
          restartPolicy: OnFailure