apiVersion: v1
kind: Secret
metadata:
  namespace: seasidefm
  name: api-secret
type: Opaque
stringData:
  MONGO_CONNECTION: "mongodb+srv://botsuro:KYZD5TEsGPlxSdTb@botsuro.easqi.mongodb.net/devDb?retryWrites=true&w=majority"
  SENTRY_DSN: "https://10531de310cf4819b51b511e894ed501@o1254187.ingest.sentry.io/6421956"